[phases.setup]
nixPkgs = ["nodejs_22", "python3", "pkg-config", "libtool", "autoconf", "automake", "openssl"]

[phases.build]
cmds = ["npm install --include=dev && npm run build"]

[start]
cmd = "NODE_ENV=production node apps/api/dist/index.js"
